"$schema" = 'https://starship.rs/config-schema.json'

[git_commit]
only_detached = false
tag_disabled = false

[kubernetes]
disabled = false
symbol = '‚õµ '

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cp|p)-(?<region>[^.]+)\.braze\.(com|eu)-opsadmin'
context_alias = '[$env] $name.$env-$region ‚ÄºÔ∏è'
style = 'bold red'
symbol = '‚õµüö® '

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cp|p)-(?<region>[^.]+)\.braze\.(com|eu)-(?<role>.+)'
context_alias = '[$env] $name.$env-$region'
style = 'bold red'
symbol = '‚õµüö® '

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>s)-(?<region>[^.]+)\.braze\.(com|eu)-opsadmin'
context_alias = '[$env] $name.$env-$region ‚ÄºÔ∏è'
style = 'bold yellow'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>s)-(?<region>[^.]+)\.braze\.(com|eu)-(?<role>.+)'
context_alias = '[$env] $name.$env-$region'
style = 'bold yellow'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cd|d)-(?<region>[^.]+)\.braze\.(com|eu)-opsadmin'
context_alias = '[$env] $name.$env-$region ‚ÄºÔ∏è'
style = 'bold green'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cd|d)-(?<region>[^.]+)\.braze\.(com|eu)-(?<role>.+)'
context_alias = '[$env] $name.$env-$region'
style = 'bold green'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>t)-(?<region>[^.]+)\.braze\.(com|eu)-opsadmin'
context_alias = '[$env] $name.$env-$region ‚ÄºÔ∏è'
style = 'bold blue'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>t)-(?<region>[^.]+)\.braze\.(com|eu)-(?<role>.+)'
context_alias = '[$env] $name.$env-$region'
style = 'bold blue'

[terraform]
format = 'via [$symbol $workspace/$version]($style) '

[time]
disabled = false